title: "CyberSec Notes"
description: "CTF writeâ€‘ups, CVEs and Bug Bounty findings"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://r3verii.github.io" # replace with your GitHub username
markdown: kramdown
kramdown:
  syntax_highlighter: none
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: "Martino Spagnuolo"
  handle: "r3verii"
  bio: "Cybersec researcher, CTF player and bug hunter."
  location: "Italy ðŸ‡®ðŸ‡¹"
  avatar: "https://avatars.githubusercontent.com/u/143962203?v=4"
  linkedin: "https://www.linkedin.com/in/martino-spagnuolo/"
  github: "https://github.com/r3verii"