title: "CyberSec Notes"
description: "CTF writeâ€‘ups, CVEs and Bug Bounty findings"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://r3verii.github.io" # replace with your GitHub username
markdown: kramdown
kramdown:
  syntax_highlighter: none
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
author:
  name: "Martino Spagnuolo"
  handle: "r3verii"
  bio: "Cybersec researcher, CTF player and bug hunter."
  location: "Italy ðŸ‡®ðŸ‡¹"
  avatar: "https://avatars.githubusercontent.com/u/143962203?v=4"
  linkedin: "https://www.linkedin.com/in/martino-spagnuolo/"
  github: "https://github.com/r3verii"

# SEO & social sharing
twitter:
  username: r3verii
social:
  name: Martino Spagnuolo
  links:
    - https://www.linkedin.com/in/martino-spagnuolo/
    - https://github.com/r3verii
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image:
        path: "/assets/img/og-home.png"
        width: 1200
        height: 630
        alt: "CyberSec Notes â€” Martino Spagnuolo (@r3verii)"